### ISSUE TITLE
Lint: Error in check_prerequisites

### ISSUE THREAD

**Issue by mr-karan** [coala-analyzer/coala#1874]
[This line](https://github.com/coala-analyzer/coala/blob/188a942e92ecc71bcd51d8329fa4fae4e2281f73/coalib/bearlib/abstractions/Lint.py#L216) fails for me with any executable

The reason is because this is not the proper way to use subprocess.call(). To rectify this either use
`subprocess.call(args, shell=True)`  or a better and more reasonable approach would be to use [shlex](https://docs.python.org/3/library/shlex.html) module and use `subprocess.call(shlex.split(args))`. 
Screenshots + Error logs attached

```
In [29]: executable
Out[29]: 'Rscript'

In [30]: arguments
Out[30]: ' -e \'library(formatR)\' -e \'formatR::tidy_source("bad.R")\' '

In [31]: prerequisite_command = executable + arguments

In [32]: prerequisite_command
Out[32]: 'Rscript -e \'library(formatR)\' -e \'formatR::tidy_source("bad.R")\' '

In [33]: subprocess.call(prerequisite_command)
FileNotFoundError: [Errno 2] No such file or directory: 'Rscript -e \'library(formatR)\' -e \'formatR::tidy_source("bad.R")\' '

```

Proof that corrected version is indeed correct:

```
In [35]: import shlex

In [36]: subprocess.call(shlex.split(prerequisite_command))
1 + 1
if (TRUE) {
    x = 1  # inline comments
} else {
    x = 2
    print("Oh no... ask the right bracket to go away!")
}
 
Out[36]: 0

```
![errorlog1](https://cloud.githubusercontent.com/assets/5689132/13724632/1877edaa-e8b2-11e5-80dd-ff54453b5352.png)
![correctlog](https://cloud.githubusercontent.com/assets/5689132/13724633/187999fc-e8b2-11e5-9b41-a7ad6b3b051b.png)

**Also**, stdout or stderr from check_prerequisites is dumped to the end user while running the bear
![version](https://cloud.githubusercontent.com/assets/5689132/13737979/6d5358d8-e9e7-11e5-8077-52b1460505b3.png)
![help](https://cloud.githubusercontent.com/assets/5689132/13737985/7a6ca416-e9e7-11e5-8797-750d30e7f720.png)

**Comment by mr-karan** [comment]
Edit:
Ok, I think we can't use Popen because we are comparing the [exit code](Hold till https://github.com/coala-analyzer/coala/issues/1874 is resolved) and Popen returns a `Popen` object. Think we should go for `subprocess.call(shlex.split(args))`

**Comment by Makman2** [comment]
I'm doing this generally also for the executable parameters/arguments inside `Lint`. So in future it is preferred to use argument sequences instead of strings (though they are still possible using `shlex.split` but it's still not recommended then) :+1:

**Comment by mr-karan** [comment]
Okay, so some executable *must* be provided a filename else they won't return with an exit code of `0`. Case in point: `ruby-lint`
```
In [3]: subprocess.call(['ruby-lint'])
You must specify at least one file to analyze
Out[3]: 1
```

Should we totally not use `subprocess.call()` and use `shutil.which()` ?

Here's what I have thought would be fine. 
```
            return True if shutil.which(''.join(command)) else fail_msg
```
But for this, [L217](https://github.com/coala-analyzer/coala/blob/master/coalib/bearlib/abstractions/Lint.py#L217) is also needed to be changed as exit code won't be `0` in these cases

**Comment by AbdealiJK** [comment]
Have you taken a look at _check_executable ?

-----Original Message-----

**Comment by mr-karan** [comment]
Oops, yeah. Alright so we don't need this in `_check_command` agreed, but how are we going to account for cases where the executable needs a filename to return exit code `0` ?

**Comment by AbdealiJK** [comment]
@mr-karan I don't ever see a place where the executable needs a filename to return exitcode 0 ...
We either use `--version` or `--help` or something else.

Basically I've never found a program where the *only* way to check if it is installed is to run it on a file.

If you have an example of such a program, we can consider this as a bug. If not, I suggest we close the issue.

Later ... if we ever do find a program like that we can think about this.
Rather, IMO - The better approach would be to tell the program writer about the bug in *his* program. Because it's just weird to not be able to check if it's installed or not.

**Comment by mr-karan** [comment]
@AbdealiJK Alright. Btw, using --help won't be a good idea as all that data is dumped to the end user while running the bear. We can use --version though as it would be almost always a one liner.

**Comment by AbdealiJK** [comment]
I don't think the stdout or stderr from check_prerequisites is shown to the user. If it is - that's a bug and we should stop it from being shown.

-----Original Message-----

**Comment by mr-karan** [comment]
It definitely is being shown: 

![version](https://cloud.githubusercontent.com/assets/5689132/13737979/6d5358d8-e9e7-11e5-8077-52b1460505b3.png)
![Uploading help.png…]()

**Comment by AbdealiJK** [comment]
Then that's a bug :)
Could you change the description in this issue ?

**Comment by sils1297** [comment]
@mr-karan any progress? I see no pending review PR, we'd love to get this for the release.
